"""empty message

Revision ID: 62224a57a59d
Revises: 63ffd8a0c7a2
Create Date: 2022-03-07 18:58:57.722492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62224a57a59d'
down_revision = '63ffd8a0c7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('website_link', sa.String(), nullable=True))
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website_link')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
